### ISSUE TITLE
v1.18.1 fails on vercel

### ISSUE THREAD

**Issue by mashaal** [vercel-community/deno#99] opened 2022-02-02 05:41 UTC
Upgrading to deno `1.18.1` fails when deploying to vercel.

Log output:

```
Downloading `deno` v1.18.1…
--
16:36:33.936 | Installed `deno`:
16:36:33.936 | deno: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by deno)
16:36:33.940 | Error: Build script failed with exit code 1
```

**Comment by TooTallNate** [comment] 2022-02-08 09:46
Ya, I can reproduce. Looks like this is already being tracked by deno [here](https://github.com/denoland/deno/issues/13516).

**Comment by kidonng** [comment] 2022-03-10 12:54
Deno just released [1.19.3](https://github.com/denoland/deno/releases/tag/v1.19.3) which fixed the upstream issue. Tested on Vercel and the build succeeds.

**Comment by TooTallNate** [comment] 2022-03-17 19:42
Update default Deno version to 1.20.1 in #105, released in `vercel-deno@1.1.2`, so I will close this issue.

**Closed by TooTallNate** 2022-03-17 19:42 UTC
